; #10 temp fan — Muawia Amir, NFC IET Multan (emu8086). Wiring + 98h/INTR notes: see README.

PORT_A      EQU 00F8h
PORT_B      EQU 00F9h
PORT_C      EQU 00FAh
PORT_CTRL   EQU 00FBh

PPI_CTRL_MIXED EQU 98h

GREEN_LED   EQU 00000001B
YELLOW_LED  EQU 00000010B
RED_LED     EQU 00000100B
MOTOR_ON    EQU 00001000B
MOTOR_HIGH  EQU 00010000B

ADC_WR      EQU 00000001B
ADC_RD      EQU 00000010B
BUZZER      EQU 00000100B
PC_OUT_MSK  EQU 00000111B
INTR_PC4    EQU 00010000B

TEMP_LOW    EQU 30
TEMP_MED    EQU 60
TEMP_HIGH   EQU 100

.DATA
    PC_SHADOW   DB 0
    MSG_INIT    DB 'Temperature-Controlled Fan System Started', 0Dh, 0Ah, '$'
    MSG_OFF     DB 'Status: FAN OFF   | GREEN  LED ON | Temp < 30C ', 0Dh, 0Ah, '$'
    MSG_LOW     DB 'Status: FAN LOW   | YELLOW LED ON | 30C - 60C  ', 0Dh, 0Ah, '$'
    MSG_HIGH    DB 'Status: FAN HIGH  | RED    LED ON | 60C - 100C ', 0Dh, 0Ah, '$'
    MSG_ALARM   DB 'STATUS: EMERGENCY! SHUTDOWN! TEMP >= 100C !!!  ', 0Dh, 0Ah, '$'
    MSG_TEMP    DB 'Current Temp: $'
    MSG_DEG     DB ' C', 0Dh, 0Ah, '$'
    MSG_SEP     DB '---------------------------------------------------', 0Dh, 0Ah, '$'

.CODE
MAIN PROC

    MOV AX, @DATA
    MOV DS, AX

    MOV AL, PPI_CTRL_MIXED
    OUT PORT_CTRL, AL

    MOV BYTE PTR PC_SHADOW, 0
    MOV AL, 00h
    OUT PORT_B, AL
    CALL WRITE_PC

    LEA DX, MSG_INIT
    MOV AH, 09h
    INT 21h

    LEA DX, MSG_SEP
    MOV AH, 09h
    INT 21h

MAIN_LOOP:

    CALL START_ADC
    CALL WAIT_ADC
    CALL READ_ADC

    MOV BL, AL
    XOR AH, AH
    MOV AL, BL
    MOV CX, 100
    MUL CX
    MOV CX, 255
    DIV CX
    MOV BL, AL

    LEA DX, MSG_TEMP
    MOV AH, 09h
    INT 21h

    CALL PRINT_TEMP

    LEA DX, MSG_DEG
    MOV AH, 09h
    INT 21h

    CMP BL, TEMP_HIGH
    JAE EMERGENCY

    CMP BL, TEMP_MED
    JAE FAN_HIGH_SPEED

    CMP BL, TEMP_LOW
    JAE FAN_LOW_SPEED

FAN_OFF:
    MOV AL, GREEN_LED
    OUT PORT_B, AL
    CALL PC_CLEAR_OUTPUTS

    LEA DX, MSG_OFF
    MOV AH, 09h
    INT 21h

    JMP DELAY_3MIN

FAN_LOW_SPEED:
    MOV AL, YELLOW_LED OR MOTOR_ON
    OUT PORT_B, AL
    CALL PC_CLEAR_OUTPUTS

    LEA DX, MSG_LOW
    MOV AH, 09h
    INT 21h

    CALL RUN_LOW_SPEED

    JMP DELAY_3MIN

FAN_HIGH_SPEED:
    MOV AL, RED_LED OR MOTOR_ON OR MOTOR_HIGH
    OUT PORT_B, AL
    CALL PC_CLEAR_OUTPUTS

    LEA DX, MSG_HIGH
    MOV AH, 09h
    INT 21h

    CALL RUN_HIGH_SPEED

    JMP DELAY_3MIN

EMERGENCY:
    MOV AL, 00h
    OUT PORT_B, AL

    MOV AL, BUZZER
    MOV PC_SHADOW, AL
    CALL WRITE_PC

    LEA DX, MSG_ALARM
    MOV AH, 09h
    INT 21h

    MOV CX, 5
FLASH_LOOP:
    MOV AL, RED_LED
    OUT PORT_B, AL
    CALL SHORT_DELAY

    MOV AL, 00h
    OUT PORT_B, AL
    CALL SHORT_DELAY

    LOOP FLASH_LOOP

    CALL LONG_DELAY
    CALL PC_CLEAR_OUTPUTS

    JMP DELAY_3MIN

DELAY_3MIN:
    LEA DX, MSG_SEP
    MOV AH, 09h
    INT 21h

    CALL DELAY_3_MINUTES

    JMP MAIN_LOOP

MAIN ENDP

WRITE_PC PROC
    PUSH AX
    MOV AL, PC_SHADOW
    AND AL, PC_OUT_MSK
    OUT PORT_C, AL
    POP AX
    RET
WRITE_PC ENDP

PC_CLEAR_OUTPUTS PROC
    MOV BYTE PTR PC_SHADOW, 0
    CALL WRITE_PC
    RET
PC_CLEAR_OUTPUTS ENDP

START_ADC PROC
    PUSH AX
    MOV AL, PC_SHADOW
    OR AL, ADC_WR
    MOV PC_SHADOW, AL
    CALL WRITE_PC
    CALL TINY_DELAY
    MOV AL, PC_SHADOW
    AND AL, 0FEh
    MOV PC_SHADOW, AL
    CALL WRITE_PC
    POP AX
    RET
START_ADC ENDP

WAIT_ADC PROC
    PUSH AX
    PUSH BX
    PUSH CX
    CALL SHORT_DELAY
    MOV BX, 0FFFFh
WADC_LOOP:
    IN AL, PORT_C
    TEST AL, INTR_PC4
    JZ WADC_DONE
    MOV CX, 40
WADC_PAUSE:
    LOOP WADC_PAUSE
    DEC BX
    JNZ WADC_LOOP
WADC_DONE:
    POP CX
    POP BX
    POP AX
    RET
WAIT_ADC ENDP

READ_ADC PROC
    PUSH BX
    MOV AL, PC_SHADOW
    OR AL, ADC_RD
    MOV PC_SHADOW, AL
    CALL WRITE_PC
    CALL TINY_DELAY
    IN AL, PORT_A
    MOV BL, AL
    MOV AL, PC_SHADOW
    AND AL, 0FDh
    MOV PC_SHADOW, AL
    CALL WRITE_PC
    MOV AL, BL
    POP BX
    RET
READ_ADC ENDP

RUN_LOW_SPEED PROC
    PUSH CX
    MOV CX, 10
LOW_CYCLE:
    MOV AL, YELLOW_LED OR MOTOR_ON
    OUT PORT_B, AL
    CALL MEDIUM_DELAY

    MOV AL, YELLOW_LED
    OUT PORT_B, AL
    CALL MEDIUM_DELAY

    LOOP LOW_CYCLE
    POP CX
    RET
RUN_LOW_SPEED ENDP

RUN_HIGH_SPEED PROC
    PUSH CX
    MOV CX, 20
HIGH_CYCLE:
    MOV AL, RED_LED OR MOTOR_ON OR MOTOR_HIGH
    OUT PORT_B, AL
    CALL SHORT_DELAY

    MOV AL, RED_LED
    OUT PORT_B, AL
    CALL SHORT_DELAY

    LOOP HIGH_CYCLE
    POP CX
    RET
RUN_HIGH_SPEED ENDP

PRINT_TEMP PROC
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX

    XOR AH, AH
    MOV AL, BL
    MOV BL, 100
    DIV BL

    CMP AL, 0
    JE SKIP_HUNDREDS
    ADD AL, '0'
    MOV DL, AL
    MOV AH, 02h
    INT 21h

SKIP_HUNDREDS:
    MOV AL, AH
    XOR AH, AH
    MOV BL, 10
    DIV BL

    MOV CH, AH

    ADD AL, '0'
    MOV DL, AL
    MOV AH, 02h
    INT 21h

    MOV DL, CH
    ADD DL, '0'
    MOV AH, 02h
    INT 21h

    POP DX
    POP CX
    POP BX
    POP AX
    RET
PRINT_TEMP ENDP

TINY_DELAY PROC
    PUSH CX
    MOV CX, 0FFh
TINY_L: LOOP TINY_L
    POP CX
    RET
TINY_DELAY ENDP

SHORT_DELAY PROC
    PUSH CX
    MOV CX, 0FFFFh
SHORT_L: LOOP SHORT_L
    POP CX
    RET
SHORT_DELAY ENDP

MEDIUM_DELAY PROC
    PUSH CX
    MOV CX, 0FFFFh
MED_OUTER:
    PUSH CX
    MOV CX, 0FFFFh
MED_INNER: LOOP MED_INNER
    POP CX
    LOOP MED_OUTER
    POP CX
    RET
MEDIUM_DELAY ENDP

LONG_DELAY PROC
    PUSH CX
    MOV CX, 30
LONG_OUTER:
    CALL MEDIUM_DELAY
    LOOP LONG_OUTER
    POP CX
    RET
LONG_DELAY ENDP

DELAY_3_MINUTES PROC
    PUSH CX
    MOV CX, 6
THREE_MIN_L:
    CALL LONG_DELAY
    LOOP THREE_MIN_L
    POP CX
    RET
DELAY_3_MINUTES ENDP

END MAIN
